### PR TITLE
 Documentation in Spanish

### PR DESCRIPTION
**Pull request by buttercubz**
A directory with the translation of the Abc use guide was added

### CODE REVIEW

**Comment by zhmushan** [comment]
Thanks for your work, but I have the following concerns:
- Once the documentation of a certain language falls behind, it will mislead some developers
- I can’t understand most languages, so I can’t check their accuracy

**Comment by buttercubz** [comment]
I understand perfectly, only that a documentation with several languages ​​helps developers who do not fully understand the English language

**Comment by zhmushan** [comment]
Actually, my English is also poor, but we have google translation. . . If there is no better reason, I will not accept this pr

Maybe it would be a good idea to provide an external repo link in the readme to point to the document in the specified language.

**Comment by buttercubz** [comment]
of course it can be a solution, I see a lot of potential in this project and I would like it to have a very clear documentation since many projects have a poor documentation.

**Pull request closed without merging**
