### PR TITLE
MiddlewareFunc return value

### PR DESCRIPTION
**Pull request by wk989898**
modify  #66

### CODE REVIEW

**Comment by zhmushan** [comment]
Thanks your pr, but need to inform: middleware returning the next function is necessary

**Comment by wk989898** [comment]
``` js
      let h = handler;
      let temp = h;
      for (const m of middleware) {
        h = m(h);
        if (h(c) === void 0) {
          h = temp;
        } else temp = h
      }
```
how does it looks

**Comment by zhmushan** [comment]
@wk989898 We shouldn't call `h`. It is a next function

**Comment by wk989898** [comment]
if middleware returning undefined ?

**Comment by wk989898** [comment]
> if middleware returning undefined ?

if `m(h)` returning undefined ,h will be undefined

**Comment by zhmushan** [comment]
@wk989898 Even if the handler exists, the context cannot be passed on correctly, so this is meaningless

**Comment by wk989898** [comment]
you are riht,maybe deepCopy  could solve it .

**Comment by zhmushan** [comment]
@wk989898 May #69 is related
We should find a way to bypass the handler and pass the context.

**Comment by wk989898** [comment]
``` js
      let h = handler;
      let MiddlewareStack = []
      let temp
      for (const m of middleware) {
        h = m(h);
        MiddlewareStack.push(h)
      }
      while (MiddlewareStack.length > 0) {
        h = MiddlewareStack.pop() as HandlerFunc
        if (temp = h(c)) return temp;
      }
      return handler(c)
```
what do you think

**Comment by zhmushan** [comment]
I don't think it's necessary to continue the discussion now, in short middleware must return next function.

**Pull request closed without merging**
